# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fai 的網站 2016
email: lazyfai@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  未諗到有咩嘢description住。
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lazyfai.github.io" # the base hostname & protocol for your site
twitter_username: lazyfai
github_username:  lazyfai

# Don't put the time in permalinks
# permalink: /:categories/:year/:month/:day/:title.html
permalink: /:year:month:day/:title/

# 5 posts per page
paginate: 5
pagination_path: posts/page:num

# Build settings
markdown: kramdown
